// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA43V80Io9v1wz8EcOKpWlq9NyIYxerEJQ',
    appId: '1:517071677917:web:dde38fcbd6962c23f56e34',
    messagingSenderId: '517071677917',
    projectId: 'campus-go-9f2bf',
    authDomain: 'campus-go-9f2bf.firebaseapp.com',
    storageBucket: 'campus-go-9f2bf.appspot.com',
    measurementId: 'G-4PXBXWSVSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeTM_NZS5P4V-a0RYWgZMcr4AByxAGajs',
    appId: '1:517071677917:android:a720e709ed9eba2ff56e34',
    messagingSenderId: '517071677917',
    projectId: 'campus-go-9f2bf',
    storageBucket: 'campus-go-9f2bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz5ZHMeJUcVLpmhjD6KUEMoVS_6OsjEAQ',
    appId: '1:517071677917:ios:f1083113b2a285dcf56e34',
    messagingSenderId: '517071677917',
    projectId: 'campus-go-9f2bf',
    storageBucket: 'campus-go-9f2bf.appspot.com',
    iosBundleId: 'com.example.campusGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz5ZHMeJUcVLpmhjD6KUEMoVS_6OsjEAQ',
    appId: '1:517071677917:ios:f1083113b2a285dcf56e34',
    messagingSenderId: '517071677917',
    projectId: 'campus-go-9f2bf',
    storageBucket: 'campus-go-9f2bf.appspot.com',
    iosBundleId: 'com.example.campusGo',
  );
}
